const {
  REACT_APP_TELEGRAM_BOT_URL,
  REACT_APP_API_BASE_URL,
  REACT_APP_GITHUB_REPO_URL,
  REACT_APP_GITHUB_REDIRECT_URL,
  REACT_APP_GITHUB_AUTHORIZE,
} = process.env;

export const TELEGRAM_BOT_URL = REACT_APP_TELEGRAM_BOT_URL;
export const API_BASE_URL = REACT_APP_API_BASE_URL;
export const GITHUB_REPO_URL = REACT_APP_GITHUB_REPO_URL;
export const GITHUB_REDIRECT_URL = REACT_APP_GITHUB_REDIRECT_URL;
export const GITHUB_AUTHORIZE = REACT_APP_GITHUB_AUTHORIZE;
