version: '3'

volumes:
  data:

services:
  # Database Machines
  database:
    build: database/
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./database/scripts:/scripts
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "5432:5432"
  
  # Cache Machines
  cache:
    build: cache/            
    command: memcached -m 64
    ports:
     - "11211:11211"
  
  # Backend Machines
  backend:
    build: backend/
    command: ./scripts/wait-for-it.sh -t 0 database:5432 -- bash -c "python manage.py migrate && gunicorn simple_project_manager.wsgi -b 0.0.0.0:8000 -w 3"
    #command: bash -c "python manage.py migrate && gunicorn simple_project_manager.wsgi -b 0.0.0.0:8000 -w 3"
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/simple_project_manager
    depends_on:
      - database
      - cache
    #ports:
    #  - "8000:8000"
    expose:
      - "8000"
  server:
    build: server/
    volumes:
      - ./backend/simple_project_manager/staticfiles:/simple_project_manager/staticfiles/
      - ./server/config/nginx:/etc/nginx/conf.d
    ports:
      - "8080:8000"
    depends_on:
      - backend
  # Frontend Machines
  # builder:
  #   build: frontend/.config/
  #   volumes: ## for build another project just add a new line
  #     - ./frontend/project_manager/:/projects/project_manager
  #     - ./frontend/client/:/projects/client        
  # project_manager:
  #   build: frontend/project_manager/
  #   volumes:
  #     - ./frontend/project_manager/build/:/usr/share/nginx/html
  #     - ./frontend/.config/nginx:/etc/nginx/conf.d
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #     - builder
  # client:
  #   build: frontend/client/
  #   volumes:
  #     - ./frontend/client/build/:/usr/share/nginx/html
  #     - ./frontend/.config/nginx:/etc/nginx/conf.d
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - server
  #     - builder
