version: "3"

volumes:
  data:

services:
  # Database Machines
  database:
    build: backend/
    image: herlanassis/postgres:9.6
    container_name: database
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./database/scripts:/scripts
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Cache Machines
  cache:
    build: cache/
    image: herlanassis/cache:1.5
    container_name: cache
    command: memcached -m 64

  # Backend Machines
  backend:
    build: backend/
    image: herlanassis/spm.backend:latest
    container_name: backend
    command: ./scripts/wait-for-it.sh -t 0 database:5432 -- bash -c "python telegram_bot.py && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn simple_project_manager.wsgi -b 0.0.0.0:8000 -w 3"
    volumes:
      - ./backend:/simple_project_manager
    depends_on:
      - database
      - cache
    env_file:
      - ./secrets.env

  server:
    build: server/
    image: herlanassis/spm.server:latest
    container_name: server
    volumes:
      - ./backend/simple_project_manager/staticfiles:/simple_project_manager/staticfiles/
    environment:
      VIRTUAL_HOST: avila.ifrn.edu.br
    depends_on:
      - backend

  # Frontend Machines
  project_manager:
    build: project_manager/
    image: herlanassis/spm.project_manager:latest
    container_name: project_manager
    depends_on:
      - server
    environment:
      VIRTUAL_HOST: manager.avila.ifrn.edu.br

  client:
    build: client/
    image: herlanassis/spm.client:latest
    container_name: client
    depends_on:
      - server
    environment:
      VIRTUAL_HOST: client.avila.ifrn.edu.br

  nginx-proxy:
    build: nginx-proxy/
    image: herlanassis/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    depends_on:
      - project_manager
      - client
