export const SAGA_ALL_WATCHERS = 'REQUEST_ALL_WATCHERS_SAGA';
export const SAGA_WATCHER = 'REQUEST_WATCHER_SAGA';
export const SAGA_CREATE_WATCHER = 'REQUEST_CREATE_WATCHER_SAGA';
export const SAGA_UPDATE_WATCHER = 'REQUEST_UPDATE_WATCHER_SAGA';

export const REQUEST_WATCHER_SUCCESS = 'REQUEST_WATCHER_SUCCESS';
export const REQUEST_WATCHER_LOADING = 'REQUEST_WATCHER_LOADING';
export const REQUEST_WATCHER_ERROR = 'REQUEST_WATCHER_ERROR';

export const REQUEST_CREATE_WATCHER_SUCCESS = 'REQUEST_CREATE_WATCHER_SUCCESS';
export const REQUEST_CREATE_WATCHER_LOADING = 'REQUEST_CREATE_WATCHER_LOADING';
export const REQUEST_CREATE_WATCHER_ERROR = 'REQUEST_CREATE_WATCHER_ERROR';

export const REQUEST_ALL_WATCHERS_SUCCESS = 'REQUEST_ALL_WATCHERS_SUCCESS';
export const REQUEST_ALL_WATCHERS_LOADING = 'REQUEST_ALL_WATCHERS_LOADING';
export const REQUEST_ALL_WATCHERS_ERROR = 'REQUEST_ALL_WATCHERS_ERROR';