# Generated by Django 2.1.5 on 2019-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='watcher',
            name='telegram_chat_id',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
