# Generated by Django 2.1.5 on 2019-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190515_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
