# Generated by Django 2.1.5 on 2019-05-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190515_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
