# Generated by Django 2.1.5 on 2019-05-15 19:47

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190515_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='email',
        ),
        migrations.AddField(
            model_name='watcher',
            name='authorization_code',
            field=models.CharField(default=apps.core.utils.create_hash, editable=False, max_length=10, unique=True),
        ),
    ]
