# Generated by Django 2.1.5 on 2019-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='message',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
