# Generated by Django 2.1.5 on 2019-05-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190518_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationHistory',
            new_name='History',
        ),
    ]
