# Generated by Django 2.1.5 on 2019-05-20 21:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20190520_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='history',
            name='sources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TELEGRAM', 'Telegram'), ('EMAIL', 'Email')], default='', editable=False, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='watcher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='notifications.Watcher'),
            preserve_default=False,
        ),
    ]
