const {
  REACT_APP_GOOGLE_REDIRECT_URL,
  REACT_APP_GOOGLE_AUTHORIZE,
  REACT_APP_TELEGRAM_BOT_URL,
  REACT_APP_API_BASE_URL,
} = process.env;

export const API_BASE_URL = REACT_APP_API_BASE_URL;
export const GOOGLE_REDIRECT_URL = REACT_APP_GOOGLE_REDIRECT_URL;
export const GOOGLE_AUTHORIZE = REACT_APP_GOOGLE_AUTHORIZE;
export const TELEGRAM_BOT_URL = REACT_APP_TELEGRAM_BOT_URL;
