export const SAGA_WATCHER = 'REQUEST_WATCHER_SAGA';
export const SAGA_UPDATE_WATCHER = 'REQUEST_UPDATE_WATCHER_SAGA';

export const REQUEST_WATCHER_SUCCESS = 'REQUEST_WATCHER_SUCCESS';
export const REQUEST_WATCHER_LOADING = 'REQUEST_WATCHER_LOADING';
export const REQUEST_WATCHER_ERROR = 'REQUEST_WATCHER_ERROR';
