# Generated by Django 2.1.5 on 2019-05-30 17:17

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('completed_on', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('is_final_release', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='TODO', max_length=64)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('expected_date', models.DateField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('project_name', models.CharField(max_length=256)),
                ('project_id', models.BigIntegerField(editable=False, unique=True)),
                ('invitation_code', models.CharField(default=apps.core.utils.create_hash, editable=False, max_length=10, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.TaskManager'),
        ),
        migrations.AddField(
            model_name='release',
            name='task_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tasks.TaskManager'),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='note',
            name='task_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskmanager_notes', to='tasks.TaskManager'),
        ),
        migrations.AlterUniqueTogether(
            name='taskmanager',
            unique_together={('owner', 'project_id')},
        ),
    ]
