# Generated by Django 2.1.5 on 2019-05-15 16:42

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='invitation_code',
            field=models.CharField(default=apps.tasks.models.create_hash, editable=False, max_length=10, unique=True),
        ),
    ]
