# Generated by Django 2.1.5 on 2019-05-31 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='conclusion_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 31, 12, 17, 33, 844715, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
