# Generated by Django 2.1.5 on 2019-06-07 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190605_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='task_manager',
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
