# Generated by Django 2.1.5 on 2019-05-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190518_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True)),
                ('is_final_relase', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tasks.TaskManager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
