# Generated by Django 2.1.5 on 2019-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190520_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
