# Generated by Django 2.1.5 on 2019-05-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskmanager_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='is_final_relase',
            new_name='is_final_release',
        ),
    ]
