# Generated by Django 2.1.5 on 2019-05-22 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20190521_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskmanager',
            unique_together={('owner', 'project_id')},
        ),
    ]
