export const SAGA_USER = 'SAGA_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_LOADING = 'REQUEST_USER_LOADING';
export const REQUEST_USER_ERROR = 'REQUEST_USER_ERROR';

export const SAGA_LIMITS = 'SAGA_LIMITS';
export const REQUEST_LIMITS_SUCCESS = 'REQUEST_LIMITS_SUCCESS';
export const REQUEST_LIMITS_LOADING = 'REQUEST_LIMITS_LOADING';
export const REQUEST_LIMITS_ERROR = 'REQUEST_LIMITS_ERROR';