export const SAGA_TASK_MANAGER = 'REQUEST_TASKMANAGER_SAGA';
export const REQUEST_TASKMANAGER_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TASKMANAGER_LOADING = 'REQUEST_TOKEN_LOADING';
export const REQUEST_TASKMANAGER_ERROR = 'REQUEST_TOKEN_ERROR';

export const SAGA_CREATE_TASKMANAGER = 'CREATE_TASKMANAGER_SAGA';
export const CREATE_TASKMANAGER_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const CREATE_TASKMANAGER_LOADING = 'REQUEST_TOKEN_LOADING';
export const CREATE_TASKMANAGER_ERROR = 'REQUEST_TOKEN_ERROR';