export const SAGA_TASK_MANAGER = 'REQUEST_TASKMANAGER_SAGA';
export const REQUEST_TASKMANAGER_SUCCESS = 'REQUEST_TASKMANAGER_SUCCESS';
export const REQUEST_TASKMANAGER_LOADING = 'REQUEST_TASKMANAGER_LOADING';
export const REQUEST_TASKMANAGER_ERROR = 'REQUEST_TASKMANAGER_ERROR';

export const SAGA_CREATE_TASKMANAGER = 'CREATE_TASKMANAGER_SAGA';
export const CREATE_TASKMANAGER_SUCCESS = 'CREATE_TASKMANAGER_SUCCESS';
export const CREATE_TASKMANAGER_LOADING = 'CREATE_TASKMANAGER_LOADING';
export const CREATE_TASKMANAGER_ERROR = 'CREATE_TASKMANAGER_ERROR';

export const SAGA_TASKS = 'REQUEST_TASKS';
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS';
export const REQUEST_TASKS_LOADING = 'REQUEST_TASKS_LOADING';
export const REQUEST_TASKS_ERROR = 'REQUEST_TASKS_ERROR';

export const SAGA_CREATE_TASK = 'SAGA_CREATE_TASK';
export const SAGA_UPDATE_TASK = 'SAGA_UPDATE_TASK';

export const CREATE_UPDATE_TASK_SUCCESS = 'CREATE_UPDATE_TASK_SUCCESS';
export const CREATE_UPDATE_TASK_LOADING = 'CREATE_UPDATE_TASK_LOADING';
export const CREATE_UPDATE_TASK_ERROR = 'CREATE_UPDATE_TASK_ERROR';
