export const SAGA_LOGOUT = 'SAGA_LOGOUT';
export const REMOVE_TOKEN_SUCCESS = 'REMOVE_TOKEN_SUCCESS';
export const REMOVE_TOKEN_LOADING = 'REMOVE_TOKEN_LOADING';
export const REMOVE_TOKEN_ERROR = 'REMOVE_TOKEN_ERROR';