export const SAGA_LOGIN = 'SAGA_LOGIN';
export const REQUEST_TOKEN_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TOKEN_LOADING = 'REQUEST_TOKEN_LOADING';
export const REQUEST_TOKEN_ERROR = 'REQUEST_TOKEN_ERROR';

export const SAGA_LOGOUT = 'SAGA_LOGOUT';
export const REMOVE_TOKEN_SUCCESS = 'REMOVE_TOKEN_SUCCESS';
export const REMOVE_TOKEN_LOADING = 'REMOVE_TOKEN_LOADING';
export const REMOVE_TOKEN_ERROR = 'REMOVE_TOKEN_ERROR';