export const SAGA_LOGIN = 'SAGA_LOGIN';
export const REQUEST_TOKEN_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TOKEN_LOADING = 'REQUEST_TOKEN_LOADING';
export const REQUEST_TOKEN_ERROR = 'REQUEST_TOKEN_ERROR';

export const SAGA_LOGOUT = 'SAGA_LOGOUT';
export const REMOVE_TOKEN_SUCCESS = 'REMOVE_TOKEN_SUCCESS';
export const REMOVE_TOKEN_LOADING = 'REMOVE_TOKEN_LOADING';
export const REMOVE_TOKEN_ERROR = 'REMOVE_TOKEN_ERROR';

export const SAGA_USER = 'SAGA_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_LOADING = 'REQUEST_USER_LOADING';
export const REQUEST_USER_ERROR = 'REQUEST_USER_ERROR';

export const SAGA_LIMITS = 'SAGA_LIMITS';
export const REQUEST_LIMITS_SUCCESS = 'REQUEST_LIMITS_SUCCESS';
export const REQUEST_LIMITS_LOADING = 'REQUEST_LIMITS_LOADING';
export const REQUEST_LIMITS_ERROR = 'REQUEST_LIMITS_ERROR';